#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.
*/
#ifndef _CFFI_USE_EMBEDDING
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47

#define _CFFI__NUM_PRIM         48
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _CFFI_NUM_EXPORTS 26

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include <inttypes.h>
#include <math.h>

void hist_uint8(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    uint32_t *histogram, uint8_t *min, uint8_t *max) {
    uint8_t working_min = 255;
    uint8_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            uint8_t val = *(uint8_t *) pixel;
            histogram[val]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void ranged_hist_uint8(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    uint32_t *histogram, uint8_t hist_min, uint8_t hist_max, uint8_t *min, uint8_t *max) {
    uint8_t working_min = 255;
    uint8_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            uint8_t val = *(uint8_t *) pixel;
            if (val >= hist_min && val <= hist_max) histogram[val - hist_min]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void masked_hist_uint8(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, uint32_t *histogram, uint8_t *min, uint8_t *max) {
        // ends are exclusive bounds
    uint8_t working_min = 255;
    uint8_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            uint8_t val = *(uint8_t *) pixel;
            histogram[val]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void masked_ranged_hist_uint8(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, uint32_t *histogram, uint8_t hist_min, uint8_t hist_max, uint8_t *min, uint8_t *max) {
        // ends are exclusive bounds
    uint8_t working_min = 255;
    uint8_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            uint8_t val = *(uint8_t *) pixel;
            if (val >= hist_min && val <= hist_max) histogram[val - hist_min]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void hist_uint16(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    uint32_t *histogram, uint8_t shift, uint16_t *min, uint16_t *max) {
    uint16_t working_min = 65535;
    uint16_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            uint16_t val = *(uint16_t *) pixel;
            histogram[val >> shift]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void ranged_hist_uint16(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    uint32_t *histogram, uint16_t n_bins, uint16_t hist_min, uint16_t hist_max, uint16_t *min, uint16_t *max) {
    uint16_t working_min = 65535;
    uint16_t working_max = 0;
    const char *row_start, *pixel;
    float bin_factor = (float) n_bins / (hist_max - hist_min);
    uint32_t *last_bin = histogram + n_bins - 1;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            uint16_t val = *(uint16_t *) pixel;
            if (val >= hist_min && val < hist_max)
                histogram[(uint16_t) (bin_factor * (val - hist_min))]++;
            else if (val == hist_max) (*last_bin)++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void masked_hist_uint16(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, uint32_t *histogram, uint8_t shift, uint16_t *min, uint16_t *max) {
        // ends are exclusive bounds
    uint16_t working_min = 65535;
    uint16_t working_max = 0;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            uint16_t val = *(uint16_t *) pixel;
            histogram[val >> shift]++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void masked_ranged_hist_uint16(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, uint32_t *histogram, uint16_t n_bins, uint16_t hist_min, uint16_t hist_max,
    uint16_t *min, uint16_t *max) {
        // ends are exclusive bounds
    uint16_t working_min = 255;
    uint16_t working_max = 0;
    const char *row_start, *pixel;
    float bin_factor = (float) n_bins / (hist_max - hist_min);
    uint32_t *last_bin = histogram + n_bins - 1;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            uint16_t val = *(uint16_t *) pixel;
            if (val >= hist_min && val < hist_max)
                histogram[(uint16_t) (bin_factor * (val - hist_min))]++;
            else if (val == hist_max) (*last_bin)++;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void minmax_float(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    float *min, float *max) {
    float working_min = INFINITY;
    float working_max = -INFINITY;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            float val = *(float *) pixel;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void masked_minmax_float(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, float *min, float *max) {
        // ends are exclusive bounds
    float working_min = INFINITY;
    float working_max = -INFINITY;
    const char *row_start, *pixel;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            float val = *(float *) pixel;
            if (val < working_min) working_min = val;
            else if (val > working_max) working_max = val;
        }
    }
    *min = working_min;
    *max = working_max;
}

void ranged_hist_float(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    uint32_t *histogram, uint16_t n_bins, float hist_min, float hist_max) {
    const char *row_start, *pixel;
    float bin_factor = (float) n_bins / (hist_max - hist_min);
    uint32_t *last_bin = histogram + n_bins - 1;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride) {
        for (pixel = row_start; pixel != row_start + cols*c_stride; pixel += c_stride) {
            float val = *(float *) pixel;
            if (val >= hist_min && val < hist_max)
                histogram[(uint16_t) (bin_factor * (val - hist_min))]++;
            else if (val == hist_max) (*last_bin)++;
        }
    }
}

void masked_ranged_hist_float(const char *image, uint16_t rows, uint16_t cols, uint32_t r_stride, uint32_t c_stride,
    const uint16_t *starts, const uint16_t *ends, uint32_t *histogram, uint16_t n_bins, float hist_min, float hist_max) {
        // ends are exclusive bounds
    const char *row_start, *pixel;
    float bin_factor = (float) n_bins / (hist_max - hist_min);
    uint32_t *last_bin = histogram + n_bins - 1;
    for (row_start = image; row_start != image + rows*r_stride; row_start += r_stride, starts++, ends++) {
        for (pixel = row_start + (*starts)*c_stride; pixel != row_start + (*ends)*c_stride; pixel += c_stride) {
            float val = *(float *) pixel;
            if (val >= hist_min && val < hist_max)
                histogram[(uint16_t) (bin_factor * (val - hist_min))]++;
            else if (val == hist_max) (*last_bin)++;
        }
    }
}

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, float *, float *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 144), // char const *
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20), // uint16_t
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 30), // float *
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, float *, float *)
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 12 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // uint16_t const *
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, uint32_t *, uint16_t, float, float)
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 22 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 24 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 25 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 4), // uint32_t *
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 30 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, uint32_t *, uint16_t, uint16_t, uint16_t, uint16_t *, uint16_t *)
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // uint16_t *
/* 46 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, uint32_t *, uint8_t *, uint8_t *)
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 50 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 51 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 52 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 55 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 56 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 69), // uint8_t *
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 59 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 60 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, uint32_t *, uint8_t, uint16_t *, uint16_t *)
/* 61 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 64 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 65 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 66 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 67 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 68 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 69 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 70 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 71 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 72 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 73 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint16_t const *, uint16_t const *, uint32_t *, uint8_t, uint8_t, uint8_t *, uint8_t *)
/* 74 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 75 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 76 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 77 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 78 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 79 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 80 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 81 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 82 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 83 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 84 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 85 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 86 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 87 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint32_t *, uint16_t, float, float)
/* 88 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 89 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 90 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 91 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 92 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 93 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 94 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 95 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 96 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 97 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 98 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint32_t *, uint16_t, uint16_t, uint16_t, uint16_t *, uint16_t *)
/* 99 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 100 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 101 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 102 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 103 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 104 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 105 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 106 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 107 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 108 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 109 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 110 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 111 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint32_t *, uint8_t *, uint8_t *)
/* 112 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 113 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 114 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 115 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 116 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 117 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 118 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 119 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 120 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 121 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint32_t *, uint8_t, uint16_t *, uint16_t *)
/* 122 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 123 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 124 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 125 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 126 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 127 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 128 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 129 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 130 */ _CFFI_OP(_CFFI_OP_NOOP, 45),
/* 131 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 132 */ _CFFI_OP(_CFFI_OP_FUNCTION, 145), // void()(char const *, uint16_t, uint16_t, uint32_t, uint32_t, uint32_t *, uint8_t, uint8_t, uint8_t *, uint8_t *)
/* 133 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 134 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 135 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20),
/* 136 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 137 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22),
/* 138 */ _CFFI_OP(_CFFI_OP_NOOP, 28),
/* 139 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 140 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 141 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 142 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 143 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 144 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 145 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_hist_uint16(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint32_t * x5, uint8_t x6, uint16_t * x7, uint16_t * x8)
{
  hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_hist_uint16(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t * x5;
  uint8_t x6;
  uint16_t * x7;
  uint16_t * x8;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;

  if (!PyArg_UnpackTuple(args, "hist_uint16", 9, 9, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(28), arg5) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, uint8_t);
  if (x6 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(45), arg7) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg8, (char **)&x8);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x8 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x8, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x8, _cffi_type(45), arg8) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_hist_uint16 _cffi_d_hist_uint16
#endif

static void _cffi_d_hist_uint8(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint32_t * x5, uint8_t * x6, uint8_t * x7)
{
  hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_hist_uint8(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t * x5;
  uint8_t * x6;
  uint8_t * x7;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;

  if (!PyArg_UnpackTuple(args, "hist_uint8", 8, 8, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(28), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(57), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(57), arg7) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_hist_uint8 _cffi_d_hist_uint8
#endif

static void _cffi_d_masked_hist_uint16(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, uint32_t * x7, uint8_t x8, uint16_t * x9, uint16_t * x10)
{
  masked_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_hist_uint16(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  uint32_t * x7;
  uint8_t x8;
  uint16_t * x9;
  uint16_t * x10;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;

  if (!PyArg_UnpackTuple(args, "masked_hist_uint16", 11, 11, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(28), arg7) < 0)
      return NULL;
  }

  x8 = _cffi_to_c_int(arg8, uint8_t);
  if (x8 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg9, (char **)&x9);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x9 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x9, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x9, _cffi_type(45), arg9) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg10, (char **)&x10);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x10 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x10, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x10, _cffi_type(45), arg10) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_hist_uint16 _cffi_d_masked_hist_uint16
#endif

static void _cffi_d_masked_hist_uint8(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, uint32_t * x7, uint8_t * x8, uint8_t * x9)
{
  masked_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_hist_uint8(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  uint32_t * x7;
  uint8_t * x8;
  uint8_t * x9;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;

  if (!PyArg_UnpackTuple(args, "masked_hist_uint8", 10, 10, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(28), arg7) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg8, (char **)&x8);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x8 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x8, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x8, _cffi_type(57), arg8) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg9, (char **)&x9);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x9 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x9, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x9, _cffi_type(57), arg9) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_hist_uint8 _cffi_d_masked_hist_uint8
#endif

static void _cffi_d_masked_minmax_float(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, float * x7, float * x8)
{
  masked_minmax_float(x0, x1, x2, x3, x4, x5, x6, x7, x8);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_minmax_float(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  float * x7;
  float * x8;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;

  if (!PyArg_UnpackTuple(args, "masked_minmax_float", 9, 9, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (float *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(6), arg7) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg8, (char **)&x8);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x8 = (float *)alloca((size_t)datasize);
    memset((void *)x8, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x8, _cffi_type(6), arg8) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_minmax_float(x0, x1, x2, x3, x4, x5, x6, x7, x8); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_minmax_float _cffi_d_masked_minmax_float
#endif

static void _cffi_d_masked_ranged_hist_float(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, uint32_t * x7, uint16_t x8, float x9, float x10)
{
  masked_ranged_hist_float(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_ranged_hist_float(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  uint32_t * x7;
  uint16_t x8;
  float x9;
  float x10;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;

  if (!PyArg_UnpackTuple(args, "masked_ranged_hist_float", 11, 11, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(28), arg7) < 0)
      return NULL;
  }

  x8 = _cffi_to_c_int(arg8, uint16_t);
  if (x8 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x9 = (float)_cffi_to_c_float(arg9);
  if (x9 == (float)-1 && PyErr_Occurred())
    return NULL;

  x10 = (float)_cffi_to_c_float(arg10);
  if (x10 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_ranged_hist_float(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_ranged_hist_float _cffi_d_masked_ranged_hist_float
#endif

static void _cffi_d_masked_ranged_hist_uint16(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, uint32_t * x7, uint16_t x8, uint16_t x9, uint16_t x10, uint16_t * x11, uint16_t * x12)
{
  masked_ranged_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_ranged_hist_uint16(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  uint32_t * x7;
  uint16_t x8;
  uint16_t x9;
  uint16_t x10;
  uint16_t * x11;
  uint16_t * x12;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;
  PyObject *arg11;
  PyObject *arg12;

  if (!PyArg_UnpackTuple(args, "masked_ranged_hist_uint16", 13, 13, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10, &arg11, &arg12))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(28), arg7) < 0)
      return NULL;
  }

  x8 = _cffi_to_c_int(arg8, uint16_t);
  if (x8 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x9 = _cffi_to_c_int(arg9, uint16_t);
  if (x9 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x10 = _cffi_to_c_int(arg10, uint16_t);
  if (x10 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg11, (char **)&x11);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x11 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x11, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x11, _cffi_type(45), arg11) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg12, (char **)&x12);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x12 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x12, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x12, _cffi_type(45), arg12) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_ranged_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_ranged_hist_uint16 _cffi_d_masked_ranged_hist_uint16
#endif

static void _cffi_d_masked_ranged_hist_uint8(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint16_t const * x5, uint16_t const * x6, uint32_t * x7, uint8_t x8, uint8_t x9, uint8_t * x10, uint8_t * x11)
{
  masked_ranged_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_masked_ranged_hist_uint8(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint16_t const * x5;
  uint16_t const * x6;
  uint32_t * x7;
  uint8_t x8;
  uint8_t x9;
  uint8_t * x10;
  uint8_t * x11;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;
  PyObject *arg11;

  if (!PyArg_UnpackTuple(args, "masked_ranged_hist_uint8", 12, 12, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10, &arg11))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(15), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (uint16_t const *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(15), arg6) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg7, (char **)&x7);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x7 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x7, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x7, _cffi_type(28), arg7) < 0)
      return NULL;
  }

  x8 = _cffi_to_c_int(arg8, uint8_t);
  if (x8 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  x9 = _cffi_to_c_int(arg9, uint8_t);
  if (x9 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg10, (char **)&x10);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x10 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x10, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x10, _cffi_type(57), arg10) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg11, (char **)&x11);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x11 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x11, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x11, _cffi_type(57), arg11) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { masked_ranged_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_masked_ranged_hist_uint8 _cffi_d_masked_ranged_hist_uint8
#endif

static void _cffi_d_minmax_float(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, float * x5, float * x6)
{
  minmax_float(x0, x1, x2, x3, x4, x5, x6);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_minmax_float(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  float * x5;
  float * x6;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;

  if (!PyArg_UnpackTuple(args, "minmax_float", 7, 7, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (float *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(6), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (float *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(6), arg6) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { minmax_float(x0, x1, x2, x3, x4, x5, x6); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_minmax_float _cffi_d_minmax_float
#endif

static void _cffi_d_ranged_hist_float(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint32_t * x5, uint16_t x6, float x7, float x8)
{
  ranged_hist_float(x0, x1, x2, x3, x4, x5, x6, x7, x8);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ranged_hist_float(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t * x5;
  uint16_t x6;
  float x7;
  float x8;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;

  if (!PyArg_UnpackTuple(args, "ranged_hist_float", 9, 9, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(28), arg5) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, uint16_t);
  if (x6 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x7 = (float)_cffi_to_c_float(arg7);
  if (x7 == (float)-1 && PyErr_Occurred())
    return NULL;

  x8 = (float)_cffi_to_c_float(arg8);
  if (x8 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ranged_hist_float(x0, x1, x2, x3, x4, x5, x6, x7, x8); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ranged_hist_float _cffi_d_ranged_hist_float
#endif

static void _cffi_d_ranged_hist_uint16(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint32_t * x5, uint16_t x6, uint16_t x7, uint16_t x8, uint16_t * x9, uint16_t * x10)
{
  ranged_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ranged_hist_uint16(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t * x5;
  uint16_t x6;
  uint16_t x7;
  uint16_t x8;
  uint16_t * x9;
  uint16_t * x10;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;

  if (!PyArg_UnpackTuple(args, "ranged_hist_uint16", 11, 11, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(28), arg5) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, uint16_t);
  if (x6 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x7 = _cffi_to_c_int(arg7, uint16_t);
  if (x7 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x8 = _cffi_to_c_int(arg8, uint16_t);
  if (x8 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg9, (char **)&x9);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x9 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x9, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x9, _cffi_type(45), arg9) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(45), arg10, (char **)&x10);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x10 = (uint16_t *)alloca((size_t)datasize);
    memset((void *)x10, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x10, _cffi_type(45), arg10) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ranged_hist_uint16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ranged_hist_uint16 _cffi_d_ranged_hist_uint16
#endif

static void _cffi_d_ranged_hist_uint8(char const * x0, uint16_t x1, uint16_t x2, uint32_t x3, uint32_t x4, uint32_t * x5, uint8_t x6, uint8_t x7, uint8_t * x8, uint8_t * x9)
{
  ranged_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ranged_hist_uint8(PyObject *self, PyObject *args)
{
  char const * x0;
  uint16_t x1;
  uint16_t x2;
  uint32_t x3;
  uint32_t x4;
  uint32_t * x5;
  uint8_t x6;
  uint8_t x7;
  uint8_t * x8;
  uint8_t * x9;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;

  if (!PyArg_UnpackTuple(args, "ranged_hist_uint8", 10, 10, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint16_t);
  if (x1 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint16_t);
  if (x2 == (uint16_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint32_t);
  if (x3 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, uint32_t);
  if (x4 == (uint32_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(28), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (uint32_t *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(28), arg5) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, uint8_t);
  if (x6 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  x7 = _cffi_to_c_int(arg7, uint8_t);
  if (x7 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg8, (char **)&x8);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x8 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x8, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x8, _cffi_type(57), arg8) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg9, (char **)&x9);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x9 = (uint8_t *)alloca((size_t)datasize);
    memset((void *)x9, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x9, _cffi_type(57), arg9) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ranged_hist_uint8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ranged_hist_uint8 _cffi_d_ranged_hist_uint8
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "hist_uint16", (void *)_cffi_f_hist_uint16, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 121), (void *)_cffi_d_hist_uint16 },
  { "hist_uint8", (void *)_cffi_f_hist_uint8, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 111), (void *)_cffi_d_hist_uint8 },
  { "masked_hist_uint16", (void *)_cffi_f_masked_hist_uint16, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 60), (void *)_cffi_d_masked_hist_uint16 },
  { "masked_hist_uint8", (void *)_cffi_f_masked_hist_uint8, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 48), (void *)_cffi_d_masked_hist_uint8 },
  { "masked_minmax_float", (void *)_cffi_f_masked_minmax_float, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d_masked_minmax_float },
  { "masked_ranged_hist_float", (void *)_cffi_f_masked_ranged_hist_float, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 20), (void *)_cffi_d_masked_ranged_hist_float },
  { "masked_ranged_hist_uint16", (void *)_cffi_f_masked_ranged_hist_uint16, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_masked_ranged_hist_uint16 },
  { "masked_ranged_hist_uint8", (void *)_cffi_f_masked_ranged_hist_uint8, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 73), (void *)_cffi_d_masked_ranged_hist_uint8 },
  { "minmax_float", (void *)_cffi_f_minmax_float, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_minmax_float },
  { "ranged_hist_float", (void *)_cffi_f_ranged_hist_float, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 87), (void *)_cffi_d_ranged_hist_float },
  { "ranged_hist_uint16", (void *)_cffi_f_ranged_hist_uint16, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 98), (void *)_cffi_d_ranged_hist_uint16 },
  { "ranged_hist_uint8", (void *)_cffi_f_ranged_hist_uint8, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 132), (void *)_cffi_d_ranged_hist_uint8 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  12,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  146,  /* num_types */
  0,  /* flags */
};

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__histogram(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__histogram(void) { return NULL; }
#  else
     init_histogram(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__histogram(void)
{
  return _cffi_init("_histogram", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_histogram(void)
{
  _cffi_init("_histogram", 0x2601, &_cffi_type_context);
}
#endif
